# Connection
host: '0.0.0.0'
port: 64738

enable_udp: false

# Sorta tech stuff
max_users: 10
max_bandwidth: 72000

welcome_text: "Welcome to Murcure powered Mumble server!"
default_room_id: 0

# SSL
private_key_path: "key.pem"
cert_path: "cert.pem"
